"""Professional A4 receipt PDF, rendered exclusively by Python backend."""
from dataclasses import dataclass
from decimal import Decimal
from io import BytesIO
from pathlib import Path
from xml.sax.saxutils import escape
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader

@dataclass(frozen=True)
class OfficialReceipt:
    number: str
    company: str
    client: str
    payment_reference: str
    payment_date: str
    issued_date: str
    payment_method: str
    amount_minor: int
    currency: str
    journal_status: str

def render_receipt_pdf(data: OfficialReceipt, *, approved_logo_path: Path) -> bytes:
    logo=Path(approved_logo_path)
    if not logo.is_file() or logo.suffix.lower() not in {".png",".jpg",".jpeg"}:
        raise ValueError("Approved CapitalBridge logo required")
    if data.journal_status!="posted" or data.currency!="LSL" or type(data.amount_minor) is not int or data.amount_minor<=0:
        raise ValueError("Only reconciled posted LSL receipts may be published")
    if not all((data.number.strip(),data.company.strip(),data.client.strip(),data.payment_reference.strip())):
        raise ValueError("Receipt identity fields required")
    output=BytesIO()
    pdf=canvas.Canvas(output,pagesize=A4,pageCompression=1)
    width,height=A4
    navy=colors.HexColor("#172D46")
    teal=colors.HexColor("#0E8388")
    pdf.setFillColor(navy)
    pdf.rect(0,height-120,width,120,fill=1,stroke=0)
    pdf.drawImage(ImageReader(str(logo)),45,height-99,width=82,height=64,preserveAspectRatio=True,anchor="c",mask="auto")
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold",20)
    pdf.drawRightString(width-45,height-58,"OFFICIAL RECEIPT")
    pdf.setFont("Helvetica",9)
    pdf.drawRightString(width-45,height-79,"Payment acknowledgement")
    pdf.setFillColor(navy)
    pdf.setFont("Helvetica-Bold",13)
    pdf.drawString(45,height-157,data.company[:72])
    pdf.setStrokeColor(teal)
    pdf.line(45,height-170,width-45,height-170)
    pairs=[
        ("Receipt number",data.number),("Received from",data.client),
        ("Payment reference",data.payment_reference),("Payment date",data.payment_date),
        ("Receipt issued",data.issued_date),("Payment method",data.payment_method),
    ]
    y=height-210
    for label,value in pairs:
        pdf.setFont("Helvetica",9)
        pdf.setFillColor(colors.HexColor("#526276"))
        pdf.drawString(45,y,label)
        pdf.setFillColor(navy)
        pdf.setFont("Helvetica-Bold",10)
        pdf.drawRightString(width-45,y,str(value)[:68])
        y-=35
    pdf.setFillColor(colors.HexColor("#E8F4F4"))
    pdf.roundRect(45,y-52,width-90,72,8,stroke=0,fill=1)
    amount=Decimal(data.amount_minor)/Decimal(100)
    pdf.setFillColor(navy)
    pdf.setFont("Helvetica-Bold",10)
    pdf.drawString(60,y-3,"TOTAL PAYMENT RECEIVED")
    pdf.setFont("Helvetica-Bold",22)
    pdf.drawRightString(width-60,y-13,f"M {amount:,.2f}")
    pdf.setFont("Helvetica",8)
    pdf.setFillColor(colors.HexColor("#64748B"))
    pdf.drawString(45,75,"Issued from verified payment records and a posted accounting journal.")
    pdf.drawString(45,62,"CapitalBridge ONE | Official receipt | Generated by backend services")
    pdf.drawRightString(width-45,62,"Page 1 of 1")
    pdf.setTitle(f"Receipt {data.number}")
    pdf.showPage()
    pdf.save()
    return output.getvalue()
